name: Generate feeds and site

on:
  push:
    branches: [ main ]
  schedule:
    # NOTE: cron は UTC。JST = UTC+9 なので、JST 9時 = UTC 0時
    # 毎日 JST 9:00-18:00 の毎時
    - cron: 0 0-9 * * *
  workflow_dispatch:

jobs:
  generate-feed:
    name: Generate Feed
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: pnpm

      - name: Install node packages
        run: pnpm install

      - name: Get date
        id: get-date
        run: |
          echo "date="$(/bin/date -u "+%Y%m%d") >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache feed images
        uses: actions/cache@v4
        with:
          path: .cache
          key: ${{ runner.os }}-feed-images-${{ steps.get-date.outputs.date }}

      - name: Generate feed
        run: pnpm feed-generate

      - name: Generate site
        run: pnpm site-build

      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # NOTE: 変更履歴が必要な場合は false に変更
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
